### ISSUE TITLE
HYB for Hybrid meetings

### ISSUE THREAD

**Issue by tintinnabulate** [code4recovery/spec#13]
This issue has been created to support "hybrid" meetings.

In the UK, I am noticing hybrid meetings pop up - that is to say, physical meetings that broadcast the meeting online over video conference.

The physical meeting has a webcam, microphone & computer screen, and publishes a video conference link for people to access the meeting online.

I don't think it's enough to use the existing spec to set the field `ONL` but not field `TC`. I think we need a separate field, `HYB` and the spec validator can check that if `HYB` is not null, then `TC` should be null and `ONL` and `video_conference_url` should be set.

P.S., what is the source code for  <https://meetingguide.org/validate> ?

**Comment by HowardL-md** [comment]
I am confused.
Hours ago looking at specs I thought I saw a `status` member whose values could be `active online-only etc` but I do not see it now. There was also a `video_conference_url`.  Now I only see `conference_url`. Am I having flashbacks? 

Anyhow, I am redoing our .json file now and looking to incorporate these things. I had added some `video_conference_url` and `status` to a couple of meetings and I was looking to see what the latest on the hybrid is. I had thought that `status` would be a good place to place HYBRID. Looking at discourse.tiaa-forum.org/t/hybrid-meeting-type-for-tsml-wordpress-plugin-and-meeting-guide-app/3685/17 I see there are some who take offence to the term "hybrid"... argh Any word will do of course but it would be nice to have something meaningful. I do think the logic you present above makes sense no matter where `HYB` is.

**Comment by joshreisner** [comment]
Hi @HowardL-md we've never had a `status` column, and it's always been `conference_url` so I don't think you're having flashbacks!

While there's a lot still to figure out about how we present online meetings especially in the WP plugin, I don't think the solution right now is to add a Hybrid meeting type. 

To clarify, we also don't have a real online meeting type either. `ONL` is an artifact that the WP plugin uses to make these meetings accessible in the Types dropdown. Meeting Guide and 12 Step Meeting List determine whether a meeting is online by whether there is a `conference_url` and/or `conference_phone` present.

The priority is to provide a good user experience to people looking for a meeting. We want to avoid situations where a web servant tags a meeting as being online but doesn't provide actual conference information. That's why both TSML and Meeting Guide don't allow users to simply tag a meeting as being "Online" as you might "Men" or "Open." Proper-looking data must be entered in those fields for it to work.

We're still working on the UI in the WP plugin and the app so this may change, but we don't want to add to the confusion by adding ornamental fields.

That said, anyone is of course welcome to use whatever types they wish on their own websites.

**Comment by tintinnabulate** [comment]
Makes sense. Thanks :)

**Comment by HowardL-md** [comment]
Yes thanks Josh. Understood all.
I really am baffled by the `status` thing though... wow
So I can be confident that the specs are being kept up to date then right?
Howard();
