### ISSUE TITLE
Proposal for managing the status of meeting locations and attendance options

### ISSUE THREAD

**Issue by tech2serve** [code4recovery/spec#17]
This proposal needs to be flushed out, and I'll continue to work on that over the next couple of days.

### Problem Statement
Many TSML users have requested more options for characterizing meetings and locations, and being able to display meetings by those characterizations. Today, our specification does not adequately capture the data necessary to track and filter meetings or locations that meet the characterizations desired by our users.

### Discussion
The characterizations most commonly requested fall into these broad groupings:

1. **_In-person_** This is our traditional meeting approach. Prior to the pandemic, any meeting data in TSML, Meeting Guide, and other apps implementing this [spec](https://github.com/code4recovery/spec) were _**in-person**_. This was the default and did not require any additional explanation.

1. **_Online/Virtual_** These meetings have been in existence for decades, but the pandemic caused their prominence to sky-rocket as physical meeting locations closed. Prevailing beliefs are that **_online/virtual_** meetings managed by geographical districts, intergroups/central offices and areas are here to stay. (Please see [this proposal](https://github.com/code4recovery/spec/tree/master/2.0)).

1. **_Hybrid_** Most often described as simultaneously happening at a physical location and through an online service such as Zoom. While it remains to be seen how successful these will be, or if the approach will remain in the long run, feedback from users continues to include management of _**hybrid**_ meetings.

1. **_Location Issues_** The pandemic raised awareness of a challenge many groups routinely face: meeting locations change or become temporarily unavailable due to weather impacts, host scheduling, or government intervention. These changes are normally temporary, but could be permanent.

1. **_Filtering/Display_** Webmasters continue to raise this issue in many forms. They want the ability to easily create and display meeting lists based on criteria that makes sense to the end user.   Filtering by type is adequate for situations where a user wants to limit the display of meetings provided in a list. However, this isn't ideal for users who want to only list meetings that are online while also adding their desired meeting types (eg., mens meetings that offer babysitting). Further, because of how types work (implemented?) in Wordpress, we would need to add an explicit type for every possible scenario, thus making the list of types more unwieldily. 

While those users providing feedback to Code for Recovery often provide _their_ solution ("Add a hybrid meeting type!") as the issue, ultimately it is this last characterization (filtering and display of information) we should focus on with the UX. 

A large number of options in a single category (i.e., our **types** field as it exists today) reduces the effectiveness of the data used therein, and makes it harder for users to experience consistent and predictable behavior from the app.

### Suggested Spec Changes

Add an `attendance_option` field for each meeting and provide three choices: 'in-person', 'online', or 'hybrid'. Default: 'in-person'.

Building on the [draft 2.0 specification](https://github.com/code4recovery/spec/tree/master/2.0) proposal calling for `online-only-meetings`, remove the geographical address dependency for any meeting with `attendance_option` set to `online`. If a meeting has `attendance_option` set to 'hybrid', require the meeting to be linked to a `location`. 

Clarify the requirement to identify the service entity responsible for the tracking the online meeting information (e.g., Area 68, District 12). _(It isn't clear to me how the draft v2.0 spec would handle this issue)_

Add a `location_status` field with two choices: 'normal', 'temporarily_closed'. The expectation should be that `location_status` automatically applies to **all** in-person and hybrid meetings at that location. Default: 'normal'

Add a `meeting_status` field with two choices: 'normal', 'temporarily_suspended'. The expectation should be that `meeting_status` only applies to the specific meeting without impact to the remaining meetings at a particular location. Default: 'normal'.

**Comment by jcookson-infoblox** [comment]
Can CSO provide a listing of geographic boundaries (lat/long) that can be incorporated?  That way if a location is falling within a specific boundary, it automatically becomes the responsibility of that area/district.

Will there be code/checks in place to ensure that a meeting with a status as "Online/Virtual" has (if it has a location set) its location status to 'temporarily closed'?  If type is set and the location is not changed, it will present confusing information to the end user.

Strictly speaking, regardless of pandemic or not, when having these options for meeting type, the location info should be representative of the type.  So ...
**In-Person** : has actual address info user can go to, `location status` reflected, `meeting status` should be reflected.
**Online/Virtual** : can have option of actual address, but we should allow non-entry for address as well.  if there is an address, then `location status` should be reflected; otherwise, we should leave that entry either as `empty, none, null`.  `meeting status` should then be _required_.
**Hybrid** : this type is for both, so we should have all info there, actual physical address, `location status` - should not be _temporarily closed_, `meeting status` should not be _temporarily suspended_.  having either of those selected beggars the question.
**Location Issues** : this can be a challenging category, but one that can be addressed with the address field containing a contact number nad information indicating that because the status, the location may change and we advise calling the contact number in advance to ensure that the meeting has not been moved.  we should also then include a note that meetings of this type are not guaranteed to be at the location we are presenting -- all that info is at the behest of the individual/groups wanting the data presented.

Filtering/Display : the above 4 are not **_meeting types_** (strictly speaking) but location types - as they all involve an element of a meetings location/physical address (the meetings content drives the meeting type, while the context of getting to it drives the location type [ie .. I can no longer drive there, so I attend virtually]) ... so why not create them as location types and then leave meeting types they way they are, that way our end customers can select the desired location type and then select the desired meeting type.

**Comment by tech2serve** [comment]
Hi @jcookson-infoblo, 

So I think my draft proposal may have caused some confusion. I don't view any of those four listed groupings as meeting types, rather they are subjects that have come up repeatedly in feedback. 

I don't consider them location types either because, quite simply, a type of "suspended" or "closed" doesn't make sense to me. 

My proposal is to view this with essentially two new categorizations: 1) _status_ (needing to capture locations and meetings separately); and 2) _attendance options_ (users can attend the meeting virtually, in-person or either way (i.e., hybrid)).

I believe location and meeting statuses need to be understood separately for the reasons I offered above. To elaborate, a location that has been shut down _should_ automatically cause the suspension of all in-person meetings at that location, while leaving the online attendance option available _if_ a particular meeting provided both online and in-person attendance options (i.e., hybrid). However, a single meeting that is temporarily suspended doesn't necessitate stopping *all* meetings at that geographical location. You are correct that a meeting that is temporarily suspended doesn't automatically shut down the online attendance option if the meeting had been a hybrid. 

Writing this has caused me to come to another solution that might be easier to implement and makes filtering/display of meeting lists quite doable:

For location data:
```json
"location_status" : "normal" | "suspended"
```

For meeting entries:
```json
"attendance_options" : "in-person" | "online" | "hybrid" | "temporarily_online_only"
``` 

**_Note:_** _I suppose a 5th attendance option for a specific meeting could be "temporarily_suspended" meaning no in-person or online meetings are happening. I'll need to think through that some more._
 
This revised approach would reduce our new data fields to two (vice three) while still providing good control over how to filter or produce meeting lists. The `temporarily_online_only` choice would allow a meeting to be flagged by the client, and could be used in a situation where the meeting itself had to be temporarily suspended (typically because the host needs the room/building for another purpose during that time) but during which other meetings at that location remain on schedule. If this option is chosen, and the meeting's previous attendance option had previous been `in-person`, entry of online details would be required.

As far as CSO's choosing the geographic bounds, I'm not 100% how GSO does this, but I'd urge caution with letting any one entity choose. I've seen a handful of situations in my travels in which a CSO (and in one case, an Area) has assumed reporting responsibility for smaller areas who did not see it as under the CSO's/Area's purview. I would not say it has been a huge issue, but it one that should be avoided. My experience is that it leads to less accurate data and duplication which confuses users. I'm not sure I have a solution to this, but I think service entities should probably be identified in the data, and some algorithm devised that prioritizes the input.

**Comment by joshreisner** [comment]
Thanks @tech2serve -- it's a challenge to reply to such a broad support ticket. Perhaps this would be better as more targeted tickets? I'll reply to as much as I can and revisit later.

* First I'd point out that this spec only describes the interchange format, not the internal data model. It's totally ok to add more metadata to your meetings in TSML. I'll get into an example of this with the In Person / Hybrid answer. What this describes is just what's the most clear and succinct way to describe meeting information from one system to another so that no data gets lost.

* For the sake of time I can't get into a full review of everything in the 2.0 spec, but I'm happy to try to talk about pieces of it. This is currently a flat array of meetings and I think it should stay that way for now. You referred to it in the context of the online meeting question (great question) and I think there are better ways of enriching the data than walling off "online only meetings" in their own array.

* I agree with your larger point about meeting types, and think there are too many of them generally. There have been a number of proposals to also break them up into cadres, like facility info vs demographic info vs meeting format, etc. I think this is an example of something that could be done on a per-app basis and doesn't have to be done in the spec itself.

* geographical address dependency: we talked about this a bit on a previous Zoom call, but I believe that location metadata is important for every meeting, including online meetings, and so to that end Meeting Guide now supports approximate locations, eg San Francisco, CA. A help document is in the works that will discuss this in further detail, but the gist of it is this: when a participating group has a meeting that meets online, they should provide an approximate location, such as a city or county, that is within their service area. This meeting will get picked up by the app but be treated slightly differently: it won't show a distance to the meeting and won't show the directions button. 12 Step Meeting List has always supported approximate addresses, but it'd be terrific if it could make some adjustments in how it displays them, so I [created a ticket](https://github.com/code4recovery/12-step-meeting-list/issues/173) for that.

**Comment by tech2serve** [comment]
> Thanks @tech2serve -- it's a challenge to reply to such a broad support ticket. Perhaps this would be better as more targeted tickets? I'll reply to as much as I can and revisit later.
> 
My goal was to get a comprehensive starting point and to flush out some of the issues. I agree that we can break this into actionable tickets once we have more consensus. Could also do through PRs of @FlipperPA's draft I suppose?

> * First I'd point out that this spec only describes the interchange format, not the internal data model. It's totally ok to add more metadata to your meetings in TSML. I'll get into an example of this with the In Person / Hybrid answer. What this describes is just what's the most clear and succinct way to describe meeting information from one system to another so that no data gets lost.

Understood. Although there are some questions I have about implementation for Meeting Guide that I'm sure will come out in the discussions. One is (to baseline the conversation) what version of the spec is current with Meeting Guide today?

> * For the sake of time I can't get into a full review of everything in the 2.0 spec, but I'm happy to try to talk about pieces of it. This is currently a flat array of meetings and I think it should stay that way for now. You referred to it in the context of the online meeting question (great question) and I think there are better ways of enriching the data than walling off "online only meetings" in their own array.

Concur. To a large extent, I wanted to acknowledge the existence of the v2.0 draft.

To what extent would adding the `attendance_option` field (in the spec) solve our ability to handle the types of issues users are having regarding online meetings/hybrids/etc? For a client app, I believe it would add a lot of flexibility, but I'll come back to that in a moment. 

Although the questionnaire has only been out for a couple of days, early responses (all of which will be shared with the team) overwhelmingly make this the top issue. And many of those responses reference both TSML and the Meeting Guide app. 

> * I agree with your larger point about meeting types, and think there are too many of them generally. There have been a number of proposals to also break them up into cadres, like facility info vs demographic info vs meeting format, etc. I think this is an example of something that could be done on a per-app basis and doesn't have to be done in the spec itself.

The only break up I want to focus on now (imo) is to improve a client app's ability to filter and display data; and I would like to be very stringent about adding more. IMO, this means pulling categorizations related to online and location status out of `types` and into other fields.  A nod towards changes on a per-app basis...but in order to be correctly handled by Meeting Guide, we'd have to revert much of the information back to `types` for the JSON feed. Doable? Sure. In the long run that becomes more to maintain...I think. 

All of that said, I also recognize we have to get GSO on board with any changes to the spec :-). So, perhaps that is the best way. We'll discuss changes with TSML and go from there. 🤷‍♂️ 

> * geographical address dependency: we talked about this a bit on a previous Zoom call, but I believe that location metadata is important for every meeting, including online meetings, and so to that end Meeting Guide now supports approximate locations, eg San Francisco, CA. A help document is in the works that will discuss this in further detail, but the gist of it is this: when a participating group has a meeting that meets online, they should provide an approximate location, such as a city or county, that is within their service area. This meeting will get picked up by the app but be treated slightly differently: it won't show a distance to the meeting and won't show the directions button. 12 Step Meeting List has always supported approximate addresses, but it'd be terrific if it could make some adjustments in how it displays them, so I [created a ticket](https://github.com/code4recovery/12-step-meeting-list/issues/173) for that.

Thank you for that! We're in agreement about keeping online meetings tied to a geographical area/region/district/office. 

And thanks for the convo.

**Comment by joshreisner** [comment]
My sense of `attendance_option` is that it reflects an interface change that's needed both in TSML and Meeting Guide, but as an API change it would introduce ambiguity.

### Interface Change
I find myself looking at a meeting list (TSML and MG) and immediately wondering 'are there any in-person meetings here yet'? It's not easy to tell! You have to look for the absence of something (address not crossed out). I think there should probably be a new dropdown. If I were designing it the options would be:

1. Online + In-Person (default)
1. Online
1. In-Person
1. Both (Hybrid)

I would try to leave out the last option but I realize it's a popular request. I just can't picture the person who is looking for a meeting and wants specifically to find a meeting that has both options.

### API Change
As an API change, adding an `attendance_option` key introduces ambiguity. Right now, the "Online Meeting" type isn't respected when importing, that's only set by the importer (Meeting Guide or TSML) when `conference_url` and/or `conference_phone` are present. That's because we don't want meetings to be "online in name only" -- we want them to have actual, usable information. It's for the same reason we don't import in-person meetings without an address. What good is listing it then?

By the same token, what if a meeting in a feed has `attendance_option` set to Online or Hybrid but no `conference_url` or `conference_phone` set? Shouldn't we then ignore it? Or what if it's set to In-Person but conversely there is a valid `conference_url` or `conference_phone`? Wouldn't that be extremely confusing if we didn't ignore it? 

For these reasons I think that this request is reflects a real need in the UI of both the plugin and the app, but would not be a good addition to the spec.

**Comment by joshreisner** [comment]
I'm not sure what this is in reference to

> Clarify the requirement to identify the service entity responsible for the tracking the online meeting information (e.g., Area 68, District 12). (It isn't clear to me how the draft v2.0 spec would handle this issue)

Each feed is provided by a single service entity, and to list a meeting in a feed is to assert responsibility.

I think @FlipperPA's intent in having an `entity` key present in his 2.0 spec was as a way to signal to the importing organization what the proper name of the service entity is, because that does change from time to time. Servants have to email GSO, for example, if they want their listing in Meeting Guide updated (name, email, phone, etc) and having it here might be more efficient.

**Comment by tech2serve** [comment]
So I agree with the idea that online meeting information must include a URL or a phone conference number at a  minimum, or it doesn't register as an online . And I do see how there is a way to make it work based on what fields are filled it.

Can you elaborate please about how you distinguish "Online + In-person" from "Hybrid"? My sense from interactions with users and the questionnaire is those are the same to them.

As far as ambiguity, I'll have to ponder that some more.

**Comment by StudioLisa** [comment]
Just came upon this and am going to reiterate the bit of back and forth btw myself and Tim on Slack upon my learning about this. I would want more user info before weighing in with a proposed solution or even change given the limits of labor available to address anything even CSS and cosmetic stuff. It's a lot easier and cheaper (labor) to do a cheap fast easy 5 user test first. Tim's gonna send me link to list to look at and then, unless there is some strong objection, I will do a little user test. Before you say 'no', understand: you won't need to do a thing and yes, I'd just come back and report on what I learned. In other words, nope - you don't have to do anything.

**Comment by joshreisner** [comment]
Hey @tech2serve I was thinking that:

Online + In Person = All meetings
Online = All online and hybrid meetings aka any meeting the user can go to online
In-person = All in-person and hybrid meetings aka any meeting the user can go to in person
Both = Hybrid meetings

**Comment by joshreisner** [comment]
I think we've agreed at this point that the spec doesn't need to change, although many of the ideas in this ticket were adopted on the front-end.
