### ISSUE TITLE
Type addition request - PINK

### ISSUE THREAD

**Issue by jcookson-infoblox** [code4recovery/spec#22]
Requesting additional type designator for "pink can", aka a special collection basket within the meeting specifically for corrections literature.
Desired abbreviation == PINK

**Comment by tech2serve** [comment]
Are you wanting these new type definitions for inside your website?

**Comment by jcookson-infoblox** [comment]
My thought was that there are a lot of meetings that do the pink can kind of 'under the radar'.  It would be nice to know if there was any meetings in the area that supported corrections based literature via giving to the pink can, which goes directly to institution literature.

**Comment by tech2serve** [comment]
I'm having trouble seeing this kind of information as a meeting type that people would search for. 

Similarly, with the CORR type, that is more of a place for the meeting. We don't have a CHUR type for churches, or a CLUB type for clubs. On the other hand. I do know some people find meetings at institutions as particularly rewarding, I just haven't seen anyone ask for this before. That makes me suspicious there isn't really a strong demand/need, and that those people are finding these special formats already.

In any case, I also recognize this needs to be a broader discussion so I'll leave these open for now.

Thanks for your comments and involvement.

**Comment by tech2serve** [comment]
Hey James (@jcookson-infoblox)--

We discussed these issues in more detail and there currently isn't support for changing the Meeting Guide spec for these requests. 

In general, a particular data type should be used by the majority of districts/intergroups, the requested type not being the norm (for example, `no smoking` is not a good type because nearly all meeting are non smoking) and expecting a typical user to want to filter for that specific type.

For many of these limited-use cases, meeting notes are a good place to add this information. They'll still be searchable and visible to the user.

These issues will remain here in the repo for potential future reference, but I'm going to close them now as I do not expect they will be implement them as types.

I would like to remind you that you can add them as custom types on your front-end/app and use them locally. 

Yis, Tim
