### ISSUE TITLE
Meeting Not Showing Up in the Meeting Guide App from our Twelve Step Meeting List JSON List

### ISSUE THREAD

**Issue by Poopdeck90210** [code4recovery/spec#42]
Greetings!

We have a meeting in our Twelve Step Meeting List plug-in JSON list that is not showing up in the Meeting Guide App.  Please assist!

Our JSON List:  https://aasaintcloud.org/wp-admin/admin-ajax.php?action=meetings
Link to the Missing Meeting:  https://aasaintcloud.org/meetings/on-the-path-to-12-step-recovery/?tsml-day=any&tsml-region=st-cloud

Thanks in advance for your help!

Alan Swanson
Chairman - St. Cloud Intergroup
1-612-865-8810
manager@aasaintcloud.org
Website:  http://aasaintcloud.org

**Comment by joshreisner** [comment]
hi alan, the listing looks good from here! there are two reasons i can think of that it might not be picked up by the app importer: 

1. conflict with another service entity (there are several in your area: mpls, st paul, and the area 35/36 website)
2. the meeting is outside what GSO designated as your service area (but since this meeting is in st cloud, i'm virtually certain it's not this)

did you contact app support? they're really the only ones who can tell you what the issue is and fix it. appsupport@aa.org

**Comment by drwingnut** [comment]
Alan:

That meeting does show in the Meeting Guide and is owned by the
aaminnesota.org feed, not your feed.  You need to coordinate with the Area
35 folks to get that resolved.
